apiVersion: isovalent.com/v1alpha1
kind: LBVIP
metadata:
  namespace: basics
  name: simple
spec:
  ipv4Request: "172.20.0.10"

--- 

apiVersion: isovalent.com/v1alpha1
kind: LBService
metadata:
  namespace: basics
  name: simple-service
spec:
  vipRef:
    name: simple
  port: 8080
  applications:
    httpProxy:
      routes:
        - backendRef:
            name: list-backends
          match:
            path:
              exact: /list
        - backendRef:
            name: simple-backends
 
---

apiVersion: isovalent.com/v1alpha1
kind: LBBackendPool
metadata:
  namespace: basics
  name: simple-backends
spec:
  backendType: IP
  backends:
    - ip: 172.21.0.11
      port: 8080
      weight: 1
    - ip: 172.21.0.12
      port: 8080
      weight: 1
  healthCheck:
    http:
      path: /healthz

---

apiVersion: isovalent.com/v1alpha1
kind: LBBackendPool
metadata:
  namespace: basics
  name: list-backends
spec:
  backendType: IP
  backends:
    - ip: 172.21.0.13
      port: 8080
      weight: 1
    - ip: 172.21.0.14
      port: 8080
      weight: 2
  healthCheck:
    http:
      path: /healthz
